language: java

# Use container-based infrastructure:
#sudo: false
sudo: required

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false

jdk:
  - oraclejdk7

# Skip "install" stage:
install: true

script: ./travis.sh
